#!/bin/bash
ver=0.1
#-----------------------------------------------------------------------#
#
# customizepkg-patching
# Applies a patch to PKGBUILD before building.
#  Daniel Oertwig <Daniel.Oertwig@googlemail.com>
#  homepage: http://www.proggen.org
#
# A modification of the original customizepkg from
# <wain@archlinux.fr>
# homepage: http://archlinux.fr
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#-----------------------------------------------------------------------#



#-----------------------------------------------------------------------#
## Some help ...
#-----------------------------------------------------------------------#
print_usage()
{
  echo "customizepkg - patching version $ver"
  echo
  echo "Without any option, this script reads PKGBUILD from the current directory and shows a diff"
  echo "between the original and the customized version of the file."
  echo "The patch to apply the changes is read from /etc/customizepkg.d/\$pkgname"
  echo
  echo "usage: customizepkg <option>"
  echo
  echo "customizepkg --version, -V       Shows version"
  echo "customizepkg --help, -h          Shows this help"
  echo "customizepkg --modify, -m        Apply the modifications"
  echo "customizepkg --vimdiff, -v       Show diff using vimdiff"
  echo
  echo "To patch, use:"
  echo "diff -up oldPKGBUILD newPKGBUILD > /etc/customizepkg.d/\$pkgname"
  echo "or"
  echo "svn diff changedPKGBUILD > /etc/customizepkg.d/\$pkgname"
  echo "or any other similar method."
  echo
  echo "Written by Daniel Oertwig <Daniel.Oertwig@googlemail.com>"
  echo "      homepage: http://www.proggen.org"
  echo " as a modification of the original customizepkg from"
  echo " <wain@archlinux.fr>"
  echo "  homepage: http://archlinux.fr"
  echo
}



print_version()
{
  echo "customizedpkg - patching version $ver"
  echo
  echo "http://www.proggen.org"
}



#-----------------------------------------------------------------------#
## MAIN PROGRAMM
#-----------------------------------------------------------------------#
VIMDIFF=0
MODIFY=0



# Parse commandline options. Modifications are made only
# if the option -m or --modify are given!
while [[ "$#" != "0" ]]; do
  case $1 in
    -h|--help)
      print_usage
      exit 0
      ;;
    --version|-V)
      print_version
      exit 0
      ;;
    -m|--modify)
      MODIFY=1
      ;;
    --vimdiff|-v)
      VIMDIFF=1
      ;;
  esac
  shift
done



# Ensure the PKGBUILD file is there and read it to
# get the pkgname variable!
if [[ ! -r ./PKGBUILD ]]; then
  echo "PKGBUILD not found!"
  exit 1
fi
source ./PKGBUILD || exit 1



# Ensure there is a patch available in the configdir
# to patch the PKGBUILD with!
if [[ ! -r "/etc/customizepkg.d/$pkgname" ]]; then
  echo "No configuration for $pkgname in /etc/customizepkg.d"
  exit 1
fi



# Save the original PKGBUILD!
cp ./PKGBUILD ./PKGBUILD.original



# Apply the patch. Revert changes if something goes
# wrong.
patch ./PKGBUILD "/etc/customizepkg.d/$pkgname"
if [[ "$?" != "0" ]]; then
  mv ./PKGBUILD.original ./PKGBUILD
  echo "Patching failed!"
  exit 1
fi



# Show the diffs
if [[ "$VIMDIFF" == "1" ]]; then
  vim -d ./PKGBUILD ./PKGBUILD.original
fi
diff -Naur ./PKGBUILD.original ./PKGBUILD



# Only if the MODIFY option was given the 
# modified file stays. Otherwise, the original
# file is used.
if [[ "$MODIFY" == "0" ]]; then
  mv ./PKGBUILD.original ./PKGBUILD
fi



# Exit gracefully :)
exit 0


